import yaml
from datetime import datetime

HEADER_TEMPLATE = '''\
/**
 * FreeRTOSConfig.h
 * Auto-generated by generate_freertos_config.py
 * Date: {date}
 *
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, modify freertos_config.yaml and regenerate.
 *
 * Reference: https://www.freertos.org/a00110.html
 */

#ifndef FREERTOS_CONFIG_H
#define FREERTOS_CONFIG_H

#include <stdint.h>
extern uint32_t SystemCoreClock;
'''

FOOTER = '''
#endif /* FREERTOS_CONFIG_H */
'''

def to_define(key, val):
    if key == "configASSERT":
        return f"#define configASSERT(x) {val}"
    if isinstance(val, bool):
        return f"#define {key} {'1' if val else '0'}"
    elif isinstance(val, str):
        return f"#define {key} {val}"
    else:
        return f"#define {key} {int(val)}"

def generate_config(yaml_data):
    lines = [HEADER_TEMPLATE.format(date=datetime.now().strftime('%Y-%m-%d %H:%M:%S'))]

    # Flatten categories
    for section in yaml_data:
        lines.append(f"\n/* {section.upper()} */")
        for key, val in yaml_data[section].items():
            if isinstance(val, dict):  # Custom complex options (like handler defines)
                for subkey, subval in val.items():
                    lines.append(to_define(subkey, subval))
            else:
                lines.append(to_define(key, val))

    lines.append(FOOTER)
    return '\n'.join(lines)


def main():
    yaml_file = "freertos_config.yaml"
    output_file = "freertos/include/FreeRTOSConfig.h"

    with open(yaml_file, 'r') as f:
        yaml_data = yaml.safe_load(f)

    config_str = generate_config(yaml_data)

    with open(output_file, 'w') as f:
        f.write(config_str)

    print(f"FreeRTOSConfig.h successfully generated at: {output_file}")


if __name__ == "__main__":
    main()
