/**
 * FreeRTOSConfig.h
 * Auto-generated by generate_freertos_config.py
 * Date: 2025-06-28 10:41:41
 *
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, modify freertos_config.yaml and regenerate.
 *
 * Reference: https://www.freertos.org/a00110.html
 */

#ifndef FREERTOS_CONFIG_H
#define FREERTOS_CONFIG_H

#include <stdint.h>
extern uint32_t SystemCoreClock;


/* FREERTOS_CONFIG */
#define configCPU_CLOCK_HZ 160000000
#define configTICK_RATE_HZ 1000
#define configMAX_PRIORITIES 5
#define configMINIMAL_STACK_SIZE 128
#define configTOTAL_HEAP_SIZE 16 * 1024
#define configMAX_TASK_NAME_LEN 16
#define configUSE_16_BIT_TICKS 0
#define configUSE_PREEMPTION 1
#define configUSE_TASK_PREEMPTION_DISABLE 0
#define configUSE_TIME_SLICING 1
#define configUSE_TICKLESS_IDLE 0
#define configSUPPORT_STATIC_ALLOCATION 0
#define configSUPPORT_DYNAMIC_ALLOCATION 1
#define configUSE_IDLE_HOOK 0
#define configUSE_TICK_HOOK 0
#define configUSE_DAEMON_TASK_STARTUP_HOOK 0
#define configENABLE_BACKWARD_COMPATIBILITY 0
#define configCHECK_FOR_STACK_OVERFLOW 2
#define configUSE_MALLOC_FAILED_HOOK 1
#define configUSE_NEWLIB_REENTRANT 0
#define configUSE_MUTEXES 1
#define configUSE_RECURSIVE_MUTEXES 1
#define configUSE_COUNTING_SEMAPHORES 1
#define configQUEUE_REGISTRY_SIZE 10
#define configUSE_TIMERS 1
#define configTIMER_TASK_PRIORITY 2
#define configTIMER_QUEUE_LENGTH 10
#define configTIMER_TASK_STACK_DEPTH 256
#define configUSE_APPLICATION_TASK_TAG 0
#define configUSE_TASK_NOTIFICATIONS 1
#define configUSE_PORT_OPTIMISED_TASK_SELECTION 1
#define configUSE_TRACE_FACILITY 1
#define configUSE_STATS_FORMATTING_FUNCTIONS 1
#define configRECORD_STACK_HIGH_ADDRESS 1
#define configGENERATE_RUN_TIME_STATS 0
#define configOPTIMIZE_FOR_RUNTIME_STATS 0
#define configTRACE_INCLUDE_USER_EVENTS 0
#define configENABLE_FPU 1
#define configENABLE_MPU 0
#define configENABLE_TRUSTZONE 0
#define configUSE_TASK_FPU_SUPPORT 2
#define configPRIO_BITS 8
#define configKERNEL_INTERRUPT_PRIORITY 255
#define configMAX_SYSCALL_INTERRUPT_PRIORITY 128
#define configLIBRARY_LOWEST_INTERRUPT_PRIORITY 255
#define configLIBRARY_MAX_SYSCALL_INTERRUPT_PRIORITY 128
#define INCLUDE_vTaskDelayUntil 1
#define INCLUDE_vTaskDelay 1
#define INCLUDE_uxTaskPriorityGet 1
#define INCLUDE_vTaskPrioritySet 1
#define INCLUDE_vTaskDelete 1
#define INCLUDE_vTaskSuspend 1
#define INCLUDE_xTaskGetSchedulerState 1
#define INCLUDE_xTaskGetIdleTaskHandle 0
#define INCLUDE_pcTaskGetTaskName 1
#define INCLUDE_eTaskGetState 1
#define INCLUDE_xTimerPendFunctionCall 1
#define INCLUDE_xTaskAbortDelay 1
#define INCLUDE_xTaskGetHandle 1
#define INCLUDE_xTaskGetCurrentTaskHandle 1
#define INCLUDE_uxTaskGetStackHighWaterMark 1
#define INCLUDE_uxTaskGetStackHighWaterMark2 1
#define INCLUDE_pxTaskGetStackStart 1
#define INCLUDE_vTaskGetInfo 1
// #define configASSERT(x) ( ( x ) ? ( void ) 0 : vAssertCalled( __FILE__, __LINE__ ) )
#define configASSERT(x) if ((x) == 0) vAssertCalled(__FILE__, __LINE__)

#endif /* FREERTOS_CONFIG_H */
